### ISSUE TITLE
Periodic spells cause chat output

### ISSUE THREAD

**Issue by klishb** [Warkdev/BestInSlotClassic#22] opened 2020-03-18 12:36 UTC
This happens whenever I enable the addon.  Maybe I could change settings, but this is what it's doing by default.

![Capture2](https://user-images.githubusercontent.com/22152810/76961303-866f3c80-68f3-11ea-9cf1-1501ec95bd08.PNG)
![Capture](https://user-images.githubusercontent.com/22152810/76961305-8707d300-68f3-11ea-8728-a7e0f8a712f4.PNG)

**Comment by Warkdev** [comment] 2020-03-18 13:41
Hello,

This is weird and the first time that any of my users is reporting it. Did you try to enable or disable other addons? Maybe there's a conflict with one of them. I'm not registering any events towards periodic spell, so I'm very surprised. 

Moreover, I barely use print statement. 

Wark

**Comment by klishb** [comment] 2020-03-18 14:18
I'm guessing it is a conflict with another addon.  I'll see if I can figure out which.  Also, not sure where to put feature requests, but can you give the UI a scaling option?

**Comment by Warkdev** [comment] 2020-03-18 15:14
Thank you.

You can open a new issue as feature request. Scaling option is something that I've considered and then denied for the time being as it requires a lot of recomputation and I'm unsure that this is easily tackled. 

Could you please insert in a new issue and explain with as much details as possible how you'd see it?

Thank you, 

Wark.

**Comment by klishb** [comment] 2020-03-18 16:03
I just went through and disabled each addon in groups of 5 or so.  I retested between each and was not able to identify an addon that was causing it.  I then disabled all addons except yours and I still have the issue.  I should have started with that step, but I really thought it was an addon conflict.

**Comment by Warkdev** [comment] 2020-03-18 16:38
Hello,

Thank you for testing. Which class are you playing and which action are you doing at that time? Which client locale are you using too? 

This is quite an incredible bug that I cannot link to anything it does so far. 

Wark

**Comment by klishb** [comment] 2020-03-18 16:42
I have only tried enabling it while playing my hunter and warrior. I provided screenshots for both.  My hunter's autoshot, pet feeding, damage over time sting, etc.  For my warrior I have plenty of examples shown in the screenshot above.

I'm using English (United States).

**Comment by Warkdev** [comment] 2020-03-18 16:49
This is even more weird. I'm also playing a warrior and never got these messages. Maybe a third party library. I'll indicate you some steps to remove useless ones that may be responsible for this.

**Comment by Warkdev** [comment] 2020-03-18 20:04
Hello again, I checked but I cannot find any line in the add-on that could generate this so far. Seems a nice bug to find out.

**Comment by klishb** [comment] 2020-03-18 20:05
Appreciate you looking in to it.

**Comment by klishb** [comment] 2020-03-18 20:06
I have an IT background if there is anything advanced you want me to troubleshoot with you.  Just no experience debugging WoW addons...

**Comment by Warkdev** [comment] 2020-03-18 20:09
Nice :) Inside the toc file, you could comment these lines and relaunch the game (not reload)

lib\LibTouristClassic-1.0\lib.xml
lib\LibStub\LibStub.lua (although this one could be in use)

**Comment by klishb** [comment] 2020-03-18 20:29
Commenting those did not have an affect on it.

**Comment by Warkdev** [comment] 2020-03-18 20:30
Is this appearing in your combat log or on your default chat window ?

**Comment by klishb** [comment] 2020-03-18 20:31
Default chat.

**Comment by Warkdev** [comment] 2020-03-18 20:37
This is giving me an headache right now, there's nothing in my code that print such statement in color in the chat. Is it only with the addon active or you're doing something specific with it at that moment ?

**Comment by Warkdev** [comment] 2020-03-18 21:03
It looks like a combat log event unhandled: https://wow.gamepedia.com/COMBAT_LOG_EVENT

**Comment by klishb** [comment] 2020-03-18 21:15
It's only active.  I'm just fighting when it happens.  Agree with your last comment.

**Comment by Warkdev** [comment] 2020-03-18 21:20
However, I'm not using the combat log in my addon, hence my diffculties to understand. Which class/spec/race are you using ?

**Comment by klishb** [comment] 2020-03-18 21:24
My hunter is Night Elf with Beast Master spec.  My 2H fury warrior is human.

**Comment by Warkdev** [comment] 2020-03-18 21:27
My setup is similar, I'm warrior fury 1H (human) and I don't have these errors.. but I've others add-on loaded. I'll test with a clean character later on and only that addon loaded.

Or it's something with an US client which will be difficult for me to test.

**Comment by klishb** [comment] 2020-03-18 21:40
Just logged on my dwarven paladin and noticed it wasn't happening at all.  With him I recently decided to try merging my default chat and combat to make more space on my screen for a healing UI.  I moved the combat log back off on it's own window and that made the default chat start spamming me with the unhandled combat log events.  If I then move the combat log back in to the main chat window as a tab it would fix it again.

**Comment by Warkdev** [comment] 2020-03-18 21:50
And did you try to disable the addon and do that exact same test ? It's maybe a bug in the WoW UI.

**Comment by Warkdev** [comment] 2020-03-18 21:53
That's an interesting finding ! I could reproduce it, thank you for reporting it :)

**Comment by Warkdev** [comment] 2020-03-18 21:53
(Dunno how and if that's linked to the add-on yet though)

**Comment by klishb** [comment] 2020-03-18 21:53
only happens when your addon is enabled.

**Comment by klishb** [comment] 2020-03-18 21:53
Oh good...that should make it easier to track down then if you can reproduce

**Comment by Warkdev** [comment] 2020-03-18 21:54
Indeed, thank you for your researches !!

**Comment by klishb** [comment] 2020-03-18 21:54
Yes and thank you

**Comment by Warkdev** [comment] 2020-03-19 21:11
I've spent my whole evening looking for this. I'm desesperate right now as I can't find what's the root cause as it doesn't make any sense..

**Comment by Warkdev** [comment] 2020-03-19 22:06
Hm I've maybe an explanation. I'll check tomorrow if that's right but I've found this: https://github.com/tomrus88/BlizzardInterfaceCode/blob/25394df4a0c05040d071435cda02a1bcc138b2f1/Interface/AddOns/Blizzard_CombatLog/Blizzard_CombatLog.lua#L197

**Comment by Warkdev** [comment] 2020-03-19 22:06
This Var could be overwritten by my add-on.

**Comment by againboy** [comment] 2020-03-20 08:48
I have this problem too.

**Comment by againboy** [comment] 2020-03-20 08:52
![image](https://user-images.githubusercontent.com/38928909/77148521-adcc3200-6aca-11ea-9952-71bef569e077.png)

**Comment by againboy** [comment] 2020-03-20 08:53
![image](https://user-images.githubusercontent.com/38928909/77148819-4367c180-6acb-11ea-8911-d5e104db1181.png)

**Comment by Warkdev** [comment] 2020-03-20 19:15
Wrong assumption... but I've found the bug !

It will be fixed in the next version. :)

**Comment by klishb** [comment] 2020-03-20 19:37
Awesome thank you!

**Comment by againboy** [comment] 2020-03-21 01:43
Awesome thank you,too!

**Comment by Warkdev** [comment] 2020-03-22 20:58
Closed with: https://github.com/Warkdev/BestInSlotClassic/commit/cc39ac6702cab29244f6315b78168e03fccd9cf9

**Closed by Warkdev** 2020-03-22 20:58 UTC
