### ISSUE TITLE
Frame empty and will not close once opened

### ISSUE THREAD

**Issue by interpim** [Warkdev/BestInSlotClassic#24] opened 2020-03-26 22:17 UTC
upon clicking the icon to open, the frame opens and i can select class, spec, tier, etc... but no items are populating, and clicking the x to close the frame doesn't work, i have to disable the addon and reload UI.

**Comment by Warkdev** [comment] 2020-03-29 19:37
Duplicate of this one: https://github.com/Warkdev/BestInSlotClassic/issues/25

**Closed by Warkdev** 2020-03-29 19:37 UTC
